# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Aktuelles
    url: /#aktuell
    weight: 10
  - name: Team
    url: /#team
    weight: 30
  - name: Leistungen
    identifier: leistungen
    weight: 40
  - name: Öffnungszeiten
    url: /#öffnungszeiten
    weight: 20
  - name: Kontakt
    url: /#kontakt
    weight: 50
  - name: Unsere Werte
    url: /#werte
    weight: 35

  - parent: leistungen
    name: HzV
    url: leistungen/hzv/
  - parent: leistungen
    name: Selbstzahler
    url: leistungen/igel/
